apiVersion: apps/v1
kind: Deployment
metadata:
  name: dialogflow-fulfillment
spec:
  selector:
    matchLabels:
      app: dialogflow-fulfillment
  replicas: 1
  template:
    metadata:
      labels:
        app: dialogflow-fulfillment
    spec:
      volumes:
      - name: google-cloud-translationkey
        secret:
          secretName: translationkey2
      containers:
      - name: dialogflow-fulfillment
        image: kalschi/gcp-df-test:1.00
        ports:
          - name: http
            containerPort: 3000
        volumeMounts:
        - name: google-cloud-translationkey
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json