apiVersion: v1
kind: Service
metadata:
  labels:
    app: dialogflow-fulfillment
  name: dialogflow-fulfillment
  namespace: default
spec:
  ports:
  - nodePort: 30301
    port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    app: dialogflow-fulfillment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}